# Generated by Django 3.2.7 on 2022-02-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='orgaization',
            new_name='organization',
        ),
    ]
