# Generated by Django 3.2.7 on 2022-02-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapps', '0002_rename_orgaization_workexperience_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
