# Generated by Django 3.2.7 on 2022-02-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapps', '0003_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
