# Generated by Django 3.2.7 on 2022-02-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapps', '0004_user_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='aboutimage/%y'),
        ),
    ]
